name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  font_awesome_flutter: ^10.8.0
  google_nav_bar: ^5.0.7
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  supabase_flutter: ^2.8.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/helpers
  filename: assets.dart
  field_prefix: